[project]
name = "turtlelab"
version = "0.3.0"
description = "An interactive graphical interface to make turtle programming easier & better"
readme = "README.md"
requires-python = ">=3.10"
dependencies = []
license = "MIT"
authors = [
  { name="Arsalan Arish", email="mail@arsalanarish.com" },
]
keywords = ["turtle", "turtleIDE", "interactiveturtle"]


[project.scripts]
turtlelab = "turtlelab.__main__:main"


[project.urls]
Repository = "https://github.com/arsalan-arish/turtlelab"


[build-system]
requires = ["uv_build>=0.9.0"]
build-backend = "uv_build"


[tool.uv.build-backend]
module-root = "src"
module-name = "turtlelab"

[tool.pyright]
ignore = ["src/", "new/"]